// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnR6xORNKV0nv7_Ftvd3_l_85BDhiGALY',
    appId: '1:587066656520:web:42763bc997b4bfa8a30ebd',
    messagingSenderId: '587066656520',
    projectId: 'nice-analyses-ua',
    authDomain: 'nice-analyses-ua.firebaseapp.com',
    storageBucket: 'nice-analyses-ua.appspot.com',
    measurementId: 'G-9K2T2K6DY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUDHeF6pJiXfETLYk_0UpurGjwQ9uVhus',
    appId: '1:587066656520:android:e94aa8a724991fc5a30ebd',
    messagingSenderId: '587066656520',
    projectId: 'nice-analyses-ua',
    storageBucket: 'nice-analyses-ua.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCjVVC3Ad9BuK-z7boNvdeaSZSgjhsPE',
    appId: '1:587066656520:ios:80239a17a81fb235a30ebd',
    messagingSenderId: '587066656520',
    projectId: 'nice-analyses-ua',
    storageBucket: 'nice-analyses-ua.appspot.com',
    iosBundleId: 'ua.com.niceAnalyses.niceAnalyses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCjVVC3Ad9BuK-z7boNvdeaSZSgjhsPE',
    appId: '1:587066656520:ios:8f40176840d08ae6a30ebd',
    messagingSenderId: '587066656520',
    projectId: 'nice-analyses-ua',
    storageBucket: 'nice-analyses-ua.appspot.com',
    iosBundleId: 'ua.com.niceAnalyses.niceAnalyses.RunnerTests',
  );
}
